services:
  - type: web
    runtime: docker
    name: follow-me-on-map
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
